name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Tous les jours à minuit
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download GitHub stats SVG
        run: |
          curl -o github-stats.svg "https://github-readme-stats-kingnomads-projects.vercel.app/api?username=kingNomad3&show_icons=true&count_private=true&theme=radical"
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add github-stats.svg
          git commit -m "update stats" || echo "no changes"
          git push
