name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Tous les jours à minuit UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download GitHub stats SVG
        run: |
          curl -L -A "Mozilla/5.0" -o github-stats.svg "https://github-readme-stats-inky-seven-91o3pa22z0.vercel.app/api?username=kingNomad3&show_icons=true&count_private=true&theme=radical"

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add github-stats.svg
          git commit -m "update stats" || echo "no changes"
          git push
